### PR TITLE
Bugfix/corp api fixes

### LINKED ISSUE #2860: Warehouse full because of wrong export of "Metal"
I accidently exported "Metal" to an "Agriculture"-coporation.
Problem is that I can not get it away from storage.
There is no "Metal" entry on the list of the UI to export it back.

So it looks like a bug.
I guess I should not be able to export "Metal" to "Agriculture" anyway (but it was selected by default).

### LINKED ISSUE #2942: Corporation API - going into debt upgrading warehouses
It's possible to use the Corporation API to buy warehouses and go significantly into debt. This can screw you over if you go into so much debt that an investment won't cover the debt. But there's reasons you might want to do this, and it gives a significant advantage. It can also be abused to drop your stock price to zero and basically then print money with a zeroed out stock price (not sure on exact details there, though, I can find out if need be)

The issue is the warehouse upgrade API call is missing a check to make sure you can actually afford the upgrade. The fix should be trivial.

After some discussion, though, we decided that we like this mechanic to an extent. We think it's fair and realistic to allow a bit of debt, but we think how much debt you can go into should be limited. Perhaps a reasonable limit is 5 or 10x the cost of the warehouse upgrade. So you can go negative only that far. Feel free to solicit other opinions on a reasonable and fair amount of debt to allow, though.

I am thinking if the API allows some limited amount of debt, though, the stock price should not be tanked by it, so there needs to be a check to prevent that. Maybe there should be a check to prevent it going to zero? I am not sure.

Potentially, as a balance measure, doing this could cause a lot of employee unhappiness? That might be more work than it's worth but seams like a reasonable penalty. 

If this is added, it should also be considered to allow someone manually playing to use the UI to go into debt buying warehouses as well... to be fair to the manual players. I think it's reasonable that the same limit be enforced in both places.

- [x] Version of the game, e.g. Bitburner v1.4.0 (a3c599e6)

### LINKED ISSUE #2943: Corporation API - Missing check that the player bought the upgrade when turning on Market TA-II
There is a missing check when turning on Market TA-II through the Corporation API. This allows you to use it basically from the very beginning without ever spending research on it, but only if you turn it on through the API. This is really unfair to manual players, and it provides significantly more income than a script trying to come up with good numbers could get.

Some effort was made to make it difficult to copy the Market TA-II code into your own script and get the same result that way. For example, ratings, quality and other vital information is not exposed in the API. Well, this bug basically makes that effort moot. It feels like it should be fixed.

Should be one or two lines to fix, as it's just missing a check that the research has been bought.

- [x] Version of the game, e.g. Bitburner v1.4.0 (a3c599e6)

### LINKED ISSUE #2965: Warehouse API can create too many products
Bitburner v1.4.0 (a3c599e6)

The ns.corporation.makeProduct() API does not enforce the limit on the number of products.

### LINKED ISSUE #2974: corporation.unlockUpgrade spends money even if upgrade already exists
The corporation 'unlockUpgrade' method does not appear to perform any checking to see if an upgrade already exists before deducting money from the corporation's account.

To reproduce the issue, simply have access to the corporation api, start a fresh corporation, and run the following:
```
ns.corporation.unlockUpgrade("Smart Supply")
ns.corporation.unlockUpgrade("Smart Supply")
ns.corporation.unlockUpgrade("Smart Supply")
```

This is on bitBurner 1.4.0 (49de4a28)

I can provide a save file if necessary, but this is pretty simple to replicate.  let me know!

### LINKED ISSUE #3059: corporation.setAutoJobAssignment to set zero workers to a job will instead set one worker to that job
v1.4.0 (49de4a28)

To reproduce:
Have a corporation, with an office that has some unassigned workers
Call corporation.setAutoJobAssignment to set a job to zero workers, where that job already has zero workers assigned.
result: one worker will be assigned to that job.

To fix the bug:
src/Corporation/OfficeSpace.ts
line 191: replace <= with <
should be: if(jobCount < amount) { ...
line 198L replace >= with >
should be: if(jobCount > amount) { ...

The bug happens because setEmployeeToJob reassigns employees even when the correct number has already been assigned

### PR DESCRIPTION
**Pull request by phyzical**
# Bug fix
* added early out in UpgradeWarehouse when not enough cash
* added checks to enforce maxProducts
* added checks to enforce export material is valid for location
* added checks for market ti reasearches* fixed the export material fix
* changed teh dev menu fund adjuster for more granular control
* added checks for smartSupply and setSmartSupply
* few random autolints

closes #2860 
closes #2943 
closes #2942 
closes #2965
closes #2974
closes #3059 

corp

annnd test script 

```
/** @param {NS} ns **/
export async function main(ns) {
	//given new corp
	// with all apis and export api access
	// and where a is argiculture
	// and where b is mining
	// and where c is software
	const industry_a = "a"
	const city = "Sector-12"
	// will error
	

	await testWrapper(ns, async () => ns.corporation.setMaterialMarketTA1(industry_a, city, "Water", true))
	await testWrapper(ns, async () => ns.corporation.setMaterialMarketTA2(industry_a,city, "Water", true))
	await testWrapper(ns, async () => {
		ns.corporation.makeProduct("c", city, "a", 1, 1)
		ns.corporation.makeProduct("c", city, "b", 1, 1)
		ns.corporation.makeProduct("c", city, "c", 1, 1)
		ns.corporation.makeProduct("c", city, "d", 1, 1)
	})

	await testWrapper(ns, async () =>  ns.corporation.setProductMarketTA1(industry_a, "a", true) )

	await testWrapper(ns, async () =>  ns.corporation.setProductMarketTA2(industry_a, "a", true) )
	await testWrapper(ns, async () => ns.corporation.exportMaterial("b", city, industry_a, city, "Metal", 1) )
	

	await testWrapper(ns, async () =>  await ns.corporation.setAutoJobAssignment(industry_a, city,"Operations", 0) )
	await testWrapper(ns, async () =>  ns.corporation.setSmartSupply(industry_a, city,true) )
	await testWrapper(ns, async () => ns.corporation.setSmartSupplyUseLeftovers(industry_a, city, "Water", true) )
	await testWrapper(ns, async () => ns.corporation.issueDividends(69) )
	await testWrapper(ns, async () => {
		while (1) {
			// will error eventually when no cash
			ns.corporation.upgradeWarehouse(industry_a, city)
			await ns.sleep(1000)
		}
	})
}

async function testWrapper(ns, func) {
	try {
		await func()
	} catch (e) {
	}
}
```

Script for testing the setAutoAssignJob

```
/** @param {NS} ns **/
export async function main(ns) {
	// division with 153 hired employees
	await ns.corporation.setAutoJobAssignment("a", "Sector-12", "Operations", 50)
	await ns.corporation.setAutoJobAssignment("a", "Sector-12", "Management", 50)
	await ns.corporation.setAutoJobAssignment("a", "Sector-12", "Business", 50)

	// case when its already correct
	await ns.corporation.setAutoJobAssignment("a", "Sector-12", "Business", 50)
	//last 3
	await ns.corporation.setAutoJobAssignment("a", "Sector-12", "Training", 3)

	//	case when there is no more
	await ns.corporation.setAutoJobAssignment("a", "Sector-12", "Unassigned", 3)
}
```

corp2

### CODE REVIEW

**Comment by phyzical** [comment]
@pigalot is there anything you can think of i may have missed with these set of fixes?

**Comment by phyzical** [comment]
yeah i agree i jumped the gun on that fix, tbh its just a bandaid to fix the one issue that someone in discord mentioned.

i will take another crack at it, (is there tests for it at the moment?) or do you just mean manual testing?

**Comment by pigalot** [comment]
just more tests in your test script

File: src/Corporation/OfficeSpace.ts [hunk 1]
```diff
@@ -184,6 +184,7 @@ export class OfficeSpace {
       }
     }
 
+    if (jobCount == amount) return false;
     if ((jobCount + unassignedCount) < amount) return false;
```
Comment (alainbryden) [inline src/Corporation/OfficeSpace.ts:188]: I think there's a fundamental problem with this entire function.

When someone calls e.g. `setEmployeeToJob(job, 2)` they're probably expecting that this will take two "unassigned" employees, and move them to this job. Implementing that would be easy.

But the way this function was designed, it will try to set employees such that the total number of employees assigned to this job is 2. So if there was already 1, it'll only add 1, and if there were already 2, it will add none. I think that's pretty weird, unless the function were named something like `setTotalNumberOfEmployeesOnJob`.

Anyway, not your problem, you're just fixing a bug (probably one of many with this method) but something to think about for another PR.

**Review by alainbryden — APPROVED** [review]

File: src/Corporation/OfficeSpace.ts (hunk 1 above)
Comment (phyzical) [reply src/Corporation/OfficeSpace.ts:188]: nah 100% im a come back to this hopefully later today, i was just tired when the fix was requested 😆  and my brain said "yep that fixes x" but i could see that it really should just be self fixable, its something todo with missing an early out in the for loop shouldnt be too hard :)

**Comment by phyzical** [comment]
@pigalot @alainbryden this should now be completed 👍
