### PR TITLE
Fix `Augmentations Left` with gang factions

### LINKED ISSUE #3118: `Augmentations Left` shortcut sometimes wrong on FactionsRoot
Earmarking this for fixing later, the augmentations left shortcut on the factions page will sometimes show incorrect counts. Seems to be most prominent in gang factions.

[source](https://canary.discord.com/channels/415207508303544321/415213413745164318/951870128419659776), [another source](https://canary.discord.com/channels/415207508303544321/415213413745164318/951727456627347517)

### PR DESCRIPTION
**Pull request by nickofolas**
Fixes #3118 

By pulling similar filter code used in `AugmentationsPage.tsx`, the `Augmentations Left` shortcut now accurately displays the number of augmentations remaining in gang factions.

<table>
  <th>Before</th>
  <th>After</th>
  <tr>
    <td>
      
    </td>
    <td>
      
    </td>
  </tr>
</table>

### CODE REVIEW

File: src/Faction/ui/FactionsRoot.tsx [hunk 1]
```diff
@@ -51,6 +58,29 @@ export function FactionsRoot(props: IProps): React.ReactElement {
...
+    const isPlayersGang = player.inGang() && player.getGangName() === faction.name;
+    let augs: string[] = [];
+
+    if (isPlayersGang) {
+      for (const augName of Object.keys(Augmentations)) {
+        if (
+          augName === AugmentationNames.NeuroFluxGovernor ||
+          augName === AugmentationNames.TheRedPill && player.bitNodeN !== 2
+        ) continue;
+        if (!Augmentations[augName].isSpecial) {
```
Comment (ApamNapat) [inline src/Faction/ui/FactionsRoot.tsx:71]: I'd put this in the `if` above 

```
      for (const augName of Object.keys(Augmentations)) {
        if (
          augName === AugmentationNames.NeuroFluxGovernor ||
          augName === AugmentationNames.TheRedPill && player.bitNodeN !== 2 ||
          Augmentations[augName].isSpecial
        ) {
          continue;
        }
        augs.push(augName)
      }
```

Comment (nickofolas) [reply src/Faction/ui/FactionsRoot.tsx]: good call

File: src/Faction/ui/FactionsRoot.tsx [hunk 2]
```diff
@@ -51,6 +58,28 @@ export function FactionsRoot(props: IProps): React.ReactElement {
     setRerender((x) => !x);
   }
 
+  const getAugsLeft = (faction: Faction, player: IPlayer): number => {
+    const isPlayersGang = player.inGang() && player.getGangName() === faction.name;
```
Comment (phyzical) [inline src/Faction/ui/FactionsRoot.tsx:62]: faction.name might cause the recovery screen if they have it open and augment, as Factions[faction] is a global thats not super safe. though its pretty easy to verify.

just run a script that timeouts out for 15 then augments with this page open

might be worth putting Factions[faction] in a variable at the top and doing an early out to avoid the issue ( thought i did this but maybe it got rolled back?)

Comment (nickofolas) [reply src/Faction/ui/FactionsRoot.tsx:62]: tested, can verify that there are no issues

**Review by phyzical — APPROVED** [review]
LGTM

**Review by ApamNapat — APPROVED** [review]
