### PR TITLE
WORK: FIX #3435 Quitting the active job now sets first remaining job as active

### LINKED ISSUE #3435: A bug that blacks out the screen
It looks like this in the video
https://youtu.be/HOwu5jew_KQ

Save file: [bitburnerSave_1649871082_BN7x0.zip](https://github.com/danielyxie/bitburner/files/8483518/bitburnerSave_1649871082_BN7x0.zip)

Steps to reproduce:
- Apply to a job
- Apply to another job
- Quit the job you secondly applied to
- Press Alt + J

Version:
Bitburner v1.6.4 (fbb99c17)

### PR DESCRIPTION
**Pull request by Snarling**
Closes #3435 .

Quitting a job no longer automatically sets the current company to "". If another job is present, the first job will become the active company for work. Alt-J should no longer lead to a black screen in this case, and the Job menu item will remain visible.

Also changes quitting a job while it is actively being worked, so instead of just setting isWorking to false directly, it does the entire finishWork process.

Performed testing locally and everything seems to work as expected. Open to suggestions on weird edge cases but I think it should just work. See issue #3435 for previous behavior.

https://user-images.githubusercontent.com/84951833/163895723-5bbd627b-8e78-4f41-aab2-f1b16bc16053.mp4

### CODE REVIEW

File: src/PersonObjects/Player/PlayerObjectGeneralMethods.tsx [hunk 1]
```diff
@@ -1870,13 +1870,12 @@ export function getNextCompanyPosition(
 
 export function quitJob(this: IPlayer, company: string): void {
   if (this.isWorking == true && this.workType.includes("Working for Company") && this.companyName == company) {
-    this.isWorking = false;
-    this.companyName = "";
+    this.finishWork(true);
   }
+  delete this.jobs[company];
```
Comment (phyzical) [inline src/PersonObjects/Player/PlayerObjectGeneralMethods.tsx:1875]: hmm would this blast multiple jobs for the same company? i guess thats not possible right?

**Review by phyzical — APPROVED** [review]
