### PR TITLE
fix to log manager take 2

### LINKED ISSUE #1775: Tail window won't pick up new run when running the same script from terminal.

### PR DESCRIPTION
**Pull request by phyzical**
added logic to pick up log when its closed via event emitter

closes #1775
Mar-21-2022 19-59-28

### CODE REVIEW

File: src/ui/React/LogBoxManager.tsx [hunk 1]
```diff
@@ -128,6 +129,23 @@ function LogWindow(props: IProps): React.ReactElement {
     setRerender((old) => !old);
   }
 
+  useEffect(
+    () =>
+      WorkerScriptStartStopEventEmitter.subscribe(() => {
+        setTimeout(() => {
```
Comment (hydroflame) [inline src/ui/React/LogBoxManager.tsx:135]: Why the timeout?

Comment (phyzical) [reply src/ui/React/LogBoxManager.tsx:135]: for some reason without it it didnt update i think it might be a race condition between the script starting up and being found as a "running script"

**Comment by GhostCrab** [comment]
This change was merged in commit 6905651b226a4a09941cfe98a08b2bb45993a16a to the dev branch, and after that, I'm getting a bug where the game locks up when I tail a script. I'm still working on simple steps to reproduce, but it looks like the script starts over and over again or logs are repeated constantly until the game stops running. When I check out the commit before this (4c64863314352d7dc6ee9a8b22de5efd92783ca8) and build, I do not see this error.
