### PR TITLE
COMPANY: FIX #3837, #3830 corrected backwards logic in quitJob function

### LINKED ISSUE #3769: Corrupt player work reputation
Bitburner v1.7.0 (00adc2ff)

If you work in the background (by pressing the "Do something else simultaneously" button) and you quit the job you are working the game doesn't stop you from working even though you quit. When trying to resolve this the game gives an error.

### LINKED ISSUE #3809: TypeError: Cannot read properties of undefined (reading 'playerReputation') (at "Work")
Bitburner v1.7.0 (00adc2ff)

Don't really know how and exactly when the error was caused. It showed when the script "workMegacorps.js" got executed.

[RECOVERY_BITBURNER_1654116025.zip](https://github.com/danielyxie/bitburner/files/8818695/RECOVERY_BITBURNER_1654116025.zip)
.

I could work around by editing the corrupt save game and disabling the company work there.
Afterwards, i was able to reproduce the problem once with "workMegacorps.js" (but i guess some other running scripts are required for reproduction); the working company was empty or undefined.
But now trying the same again i cannot reproduce it anymore; tried to run each script separately together with "workMegacorps.js" but there's always a valid company name.

### LINKED ISSUE #3826: TypeError: Cannot read properties of undefined (reading 'playerReputation') (at "Work")
### How did this happen?

I worked for a company. During working, I quit the Job. This lead to displaying the text "Working at" without showing a company name in the overview panel (the one that also your combat stats).  The button "Focus" was still visible. When I clicked that button, the game crashed.

- [x] Save file
- [ ] Minimal scripts to reproduce the issue
- [x] Steps to reproduce

### Environment

* Error: TypeError: Cannot read properties of undefined (reading 'playerReputation')
* Page: Work
* Version: v1.7.0 (b60f3da8)
* Environment: Production
* Platform: Browser
* UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.0.0 Safari/537.36
* Features: lang=de-DE cookiesEnabled=true doNotTrack=null indexedDb=true
* Source: n/a

### Save
```
Copy your save here if possible
[RECOVERY_BITBURNER_1654583228.zip](https://github.com/danielyxie/bitburner/files/8850673/RECOVERY_BITBURNER_1654583228.zip)

```

### LINKED ISSUE #3830: TypeError: Cannot read properties of undefined (reading 'playerReputation') (at "Work")
### How did this happen?

Please fill this information with details if relevant.

- [-] Save file
- [-] Minimal scripts to reproduce the issue
- [x] Steps to reproduce

### Environment

* Error: TypeError: Cannot read properties of undefined (reading 'playerReputation')
* Page: Work
* Version: v1.7.0 (b60f3da8)
* Environment: Production
* Platform: Browser
* UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.61 Safari/537.36
* Features: lang=en-US cookiesEnabled=true doNotTrack=null indexedDb=true
* Source: n/a

### Save
```
There's no need to post a save or scripts, follow steps
```

Steps to reproduce:
1. Create brand new game
2. Apply for a job inside any company, (joe's guns will do)
3. Click "Work"
4. Click "Do something else simultaneously" 
5. Quit your job while it's running in the background
6. From here on out game will crash and it will be unrecoverable, click on focus to trigger recovery mode.

### LINKED ISSUE #3837: Recovery Mode after ## TypeError: Cannot read properties of undefined (reading 'playerReputation') (at "Work")
### How did this happen?

Seems to me that changing postitions in a job while working for that same company could have caused it. The number that normally says "+11 rep" just said "+rep", then clicking "Focus" caused recovery mode. That's all I know.

Please fill this information with details if relevant.

- [] Save file ( Attatched )
- [] Minimal scripts to reproduce the issue ( No idea )
- [] Steps to reproduce below
- Log in after being idle working for eCorp as a business intern.
- Click "Apply for Business" to get a promotion.
- Click "Work" to work as the new position.
- Click "Apply for IT" to change positions.
- Click "Apply for IT" to attempt to promote, promotion failed because I didn't have the 35k rep needed.
- Click "Focus" under "Working for eCorp", where the figure that normally says reputation gained is missing.
- Recovery mode initiated.

### Environment

* Error: TypeError: Cannot read properties of undefined (reading 'playerReputation')
* Page: Work
* Version: v1.7.0 (00adc2ff)
* Environment: Production
* Platform: Steam
* UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) bitburner/1.6.4 Chrome/93.0.4577.82 Electron/14.2.4 Safari/537.36
* Features: lang=en-GB cookiesEnabled=true doNotTrack=null indexedDb=true
* Source: n/a

### Save
```
[bitburnerRecoveryError1.zip](https://github.com/danielyxie/bitburner/files/8884745/bitburnerRecoveryError1.zip)
Couldn't send directly so had to attatch as a zip instead.
```

### LINKED ISSUE #3851: Claim Reputation where you didn't work yet, from last employer.
Not sure if this is intended behavior or a bug.

- Save file not relevant
- Nor scripts
(This was done using Apply for Business Job, didn't test for other jobs)
1. Just get employed at a company, you can get to CTO or a high rank, work untill you get the reputation you need. Lets say we work 7 hours out of those 8 as CTO, so we make a lot of rep.
2. Apply for a job at a new company, where you have 0 rep. (you'll have 2 jobs for a short time)
3. Quit your old job while working on it
4. You never stopped working, so from "Working at *last employer*" it goes straight to "Working at *new employer*", and all the rep you gained stays there. You can now wait for the 8h to finish and claim all the rep previously earned working for the last employer.
(This can also be done early before the 8 hours passed, by pressing the stop working, however it is still affected by the penalty)

[some pictures that may help understand this better](https://imgur.com/a/J5pqkxy)

- Game Version : Steam Version Bitburner v1.7.0 (00adc2ff)
- Windows 10, latest updates

### LINKED ISSUE #3855: [BUG]TypeError: Cannot read properties of undefined (reading 'playerReputation') (at "Work")
### How did this happen?

- Join a job.
- Start working.
- Press the button "Do something simultaneously".
- Quit from that job.
- Press the button "focus".

### Environment

* Error: TypeError: Cannot read properties of undefined (reading 'playerReputation')
* Page: Work
* Version: v1.7.0 (00adc2ff)
* Environment: Production
* Platform: Steam
* UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) bitburner/1.6.4 Chrome/93.0.4577.82 Electron/14.2.4 Safari/537.36
* Features: lang=en-US cookiesEnabled=true doNotTrack=null indexedDb=true
* Source: n/a

### LINKED ISSUE #3856: Applying for or quitting a job cancels any in-progress task
Applying for a new job, or quitting an existing job, will cancel any in-progress grafting (the real problem) as well as studying, gym workouts, faction work, or creating a program. Bladeburner tasks are not affected by this and will maintain progress during a job application / quit.

Also, if you quit a job while doing a task that affects your stats, you'll also get a message about how you wrapped up your job shift, with an elapsed time that matches up with when you started whatever you were actually doing, and work "earnings" based on what you were actually doing.

Version: Bitburner v1.7.0 (b60f3da8)

Steps to reproduce: 

- Start a non-job related task, like studying at university.
- Apply for a job at foodnstuff. Your study session will get canceled.
Or:
- Have a job at foodnstuff.
- Start a non-job related task, like studying at university.
- Quit your job at foodnstuff.  Your study session will get canceled, and the data for the study session will get put into the template for quitting a job shift early.

### LINKED ISSUE #3857: TypeError: Cannot read properties of undefined (reading 'playerReputation') (at "Work")
### How did this happen?

Please fill this information with details if relevant.

- [x] Save file
- [ ] Minimal scripts to reproduce the issue
- [ ] Steps to reproduce

### Environment

* Error: TypeError: Cannot read properties of undefined (reading 'playerReputation')
* Page: Work
* Version: v1.7.0 (00adc2ff)
* Environment: Production
* Platform: Steam
* UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) bitburner/1.6.4 Chrome/93.0.4577.82 Electron/14.2.4 Safari/537.36
* Features: lang=de cookiesEnabled=true doNotTrack=null indexedDb=true
* Source: n/a
[RECOVERY_BITBURNER_1655843386.zip](https://github.com/danielyxie/bitburner/files/8952635/RECOVERY_BITBURNER_1655843386.zip)

### LINKED ISSUE #3877: Quitting got me fired
### How did this happen?

Please fill this information with details if relevant.

- [❌] Save file
- [❌] Minimal scripts to reproduce the issue
- [✔️] Steps to reproduce
---
- join Joe's Guns as an employee after reluctantly jumping into a new BN
- start working for Joe
- unfocus your stimulating new career choice
- realize that you'd rather watch paint dry
- literally "Quit" Joe's
  - first anomaly's here; after quitting, the Overview still shows the unfocused work
- be stupid and wonder what "Focus"ing work that you've summarily walked out on will do
- watch it all burn
- click the button to tell Github about it
---
### Environment

* Error: TypeError: Cannot read properties of undefined (reading 'playerReputation')
* Page: Work
* Version: v1.7.0 (00adc2ff)
* Environment: Production
* Platform: Steam
* UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) bitburner/1.6.4 Chrome/93.0.4577.82 Electron/14.2.4 Safari/537.36
* Features: lang=en-US cookiesEnabled=true doNotTrack=null indexedDb=true
* Source: n/a

### LINKED ISSUE #3878: BN5, working for company, Quit, then much time later, clicked on Focus on task and it crashed.
# include (where relevant)

- [x] Save file
- [ ] Minimal scripts to reproduce the issue
- [x] Steps to reproduce
 * I _think_ I was in BN5 (AI). Was working for Joes guns for a while, quit there. was working on rewriting some scripts. clicked the (focus) button in the status bar. and it crashed.
- [x] Version of the game, e.g. Bitburner v1.7.0 (b60f3da8)
[RECOVERY_BITBURNER_1656608884.zip](https://github.com/danielyxie/bitburner/files/9021957/RECOVERY_BITBURNER_1656608884.zip)

### PR DESCRIPTION
**Pull request by Snarling**
Fixes #3830
Fixes #3837 (or at least seems to)

If you're currently doing company work, and quitting from the same company that is active, then it will finish your work shift before deleting the job. Previously, it would only attempt to finish the work shift if you _weren't_ doing company work, but were quitting from your active company.

Edit: Fixes #3851, Fixes #3855, Fixes #3826, Fixes #3809, Fixes #3769, Fixes #3857, Fixes #3856, Fixes #3877, Fixes #3878

### CODE REVIEW

**Review by phyzical — APPROVED** [review]

File: src/PersonObjects/Player/PlayerObjectGeneralMethods.tsx [hunk 1]
```diff
@@ -1854,7 +1854,7 @@ export function getNextCompanyPosition(
 }
 
 export function quitJob(this: IPlayer, company: string, _sing = false): void {
-  if (this.isWorking == true && this.workType !== WorkType.Company && this.companyName == company) {
+  if (this.isWorking === true && this.workType === WorkType.Company && this.companyName === company) {
```
Comment (ilkecan) [inline src/PersonObjects/Player/PlayerObjectGeneralMethods.tsx:1857]: Because of the logic in the current version, part-time jobs (`WorkType.CompanyPartTime`) finish when you quit the company but not full-time jobs (`WorkType.Company`). After this change the full-time jobs works but not the part-time ones. We should check that `this.workType` is either part-time or full-time like in [here](https://github.com/danielyxie/bitburner/pull/3874/files#diff-812beaabeb59591d8e0779204c7089eeda40d5ebbc2b80e017ef246285f91a7eR1859).

Comment (Snarling) [reply src/PersonObjects/Player/PlayerObjectGeneralMethods.tsx]: Good catch! Updated.
