### PR TITLE
Sleeve fix for when faction isnt found

### LINKED ISSUE #2685: TypeError: Cannot read properties of undefined (reading 'getInfo') (at "Sleeves")
- [x ] Save file
[RECOVERY_BITBURNER_1642459063.txt](https://github.com/danielyxie/bitburner/files/7884987/RECOVERY_BITBURNER_1642459063.txt)
- [ ] Minimal scripts to reproduce the issue
- [ x] Steps to reproduce
Went from gangs to the sleeves page
- [x ] Version of the game, e.g. Bitburner v1.3.0 (216bf616)
Version: v1.3.0 (949f5549)
[RECOVERY_BITBURNER_1642459063.txt](https://github.com/danielyxie/bitburner/files/7884987/RECOVERY_BITBURNER_1642459063.txt)

### Environment

* Error: TypeError: Cannot read properties of undefined (reading 'getInfo')
* Page: Sleeves
* Version: v1.3.0 (949f5549)
* Environment: Production
* Platform: Steam
* UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) bitburner/1.0.0 Chrome/93.0.4577.82 Electron/14.0.2 Safari/537.36
* Features: lang=de cookiesEnabled=true doNotTrack=null indexedDb=true
* Source: n/a

### LINKED ISSUE #2832: [BUG] Sleeves - TypeError: Cannot read properties of undefined (reading 'getInfo')
### How did this happen?
Best guess is that I had 2 sleeves tasks open to "Work for faction - Daedalus - Field work" (because I realized there was a better choice after opening it up on a random sleeve - but hadn't hit set, so I just opened it on the better one and hit set). Recovery mode was entered the moment I hit the set task button.

Please fill this information with details if relevant.
I don't have Sleeve scripts, so I'm assuming it's not one of my scripts, but just in case,
My scripts can be found here: https://github.com/zeddrak/bitburner-scripts (allinone.js contains all the scripts in one file for easy searching - it's also the only one that's up to date.)

### Environment

* Error: TypeError: Cannot read properties of undefined (reading 'getInfo')
* Page: Sleeves
* Version: v1.4.0 (1e126d40)
* Environment: Production
* Platform: Steam
* UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) bitburner/1.0.0 Chrome/93.0.4577.82 Electron/14.0.2 Safari/537.36
* Features: lang=en-US cookiesEnabled=true doNotTrack=null indexedDb=true
* Source: n/a

### Save
```
Tried to include save here, but it threw an error when I tried to submit it - something about a 65536 character limit,,,
```

### LINKED ISSUE #2908: BN2 - Cannot access Sleeves after starting gang (Syndicate)
# DELETE THIS AFTER READING

# include (where relevant)

- [ attached ] Save file
- [Autofarm.ns / purchase-server script for 2TB ] Minimal scripts to reproduce the issue
- [ I created my first gang on BN2, recruited a member and wanted to click on sleeves and boom, dead when clicked ] Steps to reproduce
- [ * Error: TypeError: Cannot read properties of undefined (reading 'getInfo')
* Page: Sleeves
* Version: v1.4.0 (49de4a28)
* Environment: Production
* Platform: Steam
* UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) bitburner/1.0.0 Chrome/93.0.4577.82 Electron/14.0.2 Safari/537.36
* Features: lang=en-US cookiesEnabled=true doNotTrack=null indexedDb=true
* Source: n/a ] Version of the game, e.g. Bitburner v1.3.0 (216bf616)
[bitburnererror.zip](https://github.com/danielyxie/bitburner/files/7997227/bitburnererror.zip)

### LINKED ISSUE #2976: Crash When Changing Sleeve Tasks
- [X] Save file
[RECOVERY_BITBURNER_1644807012.zip](https://github.com/danielyxie/bitburner/files/8057550/RECOVERY_BITBURNER_1644807012.zip)
- [X] Steps to reproduce

1. Tell a sleeve to begin working for a faction, but don't Set Task.
2. Tell another sleeve to begin working for a faction, and Set Task.
3. Experience crash.

I have a video capturing the behavior if needed.

### Environment

* Error: TypeError: Cannot read properties of undefined (reading 'getInfo')
* Page: Sleeves
* Version: v1.4.0 (49de4a28)
* Environment: Production
* Platform: Steam
* UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) bitburner/1.0.0 Chrome/93.0.4577.82 Electron/14.0.2 Safari/537.36
* Features: lang=en-US cookiesEnabled=true doNotTrack=null indexedDb=true
* Source: n/a

### PR DESCRIPTION
**Pull request by phyzical**
* added early out for when faction isnt found

closes #2832
closes #2976
closes #2908
closes #2685

### CODE REVIEW

File: src/PersonObjects/Sleeve/Sleeve.ts [hunk 1]
```diff
@@ -859,10 +859,8 @@ export class Sleeve extends Person {
    * Returns boolean indicating success
    */
   workForFaction(p: IPlayer, factionName: string, workType: string): boolean {
-    if (factionName === "") {
-      return false;
-    }
-    if (!(Factions[factionName] instanceof Faction) || !p.factions.includes(factionName)) {
+    const faction = Factions[factionName]
+    if (factionName === "" || !faction || !(faction instanceof Faction) || !p.factions.includes(factionName)) {
```
Comment (ApamNapat) [inline src/PersonObjects/Sleeve/Sleeve.ts:863]: Doesn't `!p.factions.includes(factionName)` cover the `factionName === ""` case? Or is it possible for the former to return `false` when the latter would return `true`? Same goes for `!faction` and `!(faction instanceof Faction)`

Comment (phyzical) [reply src/PersonObjects/Sleeve/Sleeve.ts:863]: yeah i had these thoughts too... but then i'm not sure how some users could end up running into the issue further down (the .getInfo on undefined).

 maybe by storing the faction earlier now it wouldn't be an issue.

i guess i was thinking well, it might be redundant but better safe than sorry.

issue is this bug is a PIA to replicate even with user save files it seems.
